<a href="https://colab.research.google.com/github/fnzl54/Python_study/blob/main/Python9_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.19.5'

# 배열 생성

In [3]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[2])

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 3


In [4]:
a2 = np.array([ [1,2,3], [4,5,6], [7,8,9]])
print(a2)
print(type(a2))
print(a2.shape)
print(a2[0], a2[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)
[1 2 3] 8


In [5]:
a3 = np.array([ [ [1,2,3], [4,5,6], [7,8,9] ],
                [ [1,2,3], [4,5,6], [7,8,9] ],
                [ [1,2,3], [4,5,6], [7,8,9] ] ])
print(a3)
print(type(a3))
print(a3.shape)
print(a3[0], a3[2,1,1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
(3, 3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]] 5


In [6]:
np.full((3,3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

In [7]:
np.arange(1, 5, 0.25)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75])

In [8]:
np.random.random((3,3))

array([[0.18714178, 0.62809742, 0.34104743],
       [0.60196862, 0.56368171, 0.84337973],
       [0.71729342, 0.62256697, 0.39233031]])

In [9]:
np.random.randint( 1, 100, (3, 5) )

array([[23, 61, 25, 77, 82],
       [29, 48, 29, 28, 12],
       [43, 21, 61, 51, 30]])

In [10]:
np.ones((3,3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [14]:
date = np.array('2022-01-01 12:00', dtype = np.datetime64)
date

array('2022-01-01T12:00', dtype='datetime64[m]')

In [15]:
# 날짜 연산 가능
date + 1

numpy.datetime64('2022-01-01T12:01')

# 배열 조회

In [16]:
def array_info(array):
  print(array)
  print(array.ndim)
  print(array.shape)
  print(array.dtype)
  print(array.size)
  print(array.itemsize)
  print(array.nbytes)
  print(array.strides)

In [17]:
array_info(a1)

[1 2 3 4 5]
1
(5,)
int64
5
8
40
(8,)


In [18]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
int64
9
8
72
(24, 8)


In [19]:
print(a1)
print(a1[2])
print(a1[-3])

[1 2 3 4 5]
3
3


In [20]:
print(a1)
print(a1[0:2])
print(a1[3:])

[1 2 3 4 5]
[1 2]
[4 5]


In [23]:
print(a2)
print(a2[0:2, :])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


# 배열 삽입, 삭제, 복사, 변환, 재구조화, 크기변경, 추가, 연결, 분할

In [25]:
print(a1)
b1 = np.insert(a1, 2, 10)
print(b1)

[1 2 3 4 5]
[ 1  2 10  3  4  5]


In [27]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


In [28]:
print(a2)
b2 = np.delete(a2, 1, axis=0)
c2 = np.delete(a2, 1, axis=1)
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]


In [30]:
print(a2)
a2_sub = a2[:2, :2].copy()
print(a2_sub)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


In [32]:
print(a2)
print(a2.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [37]:
n1 = np.arange(1,19,2)
print(n1)
print(n1.reshape(3,3))

[ 1  3  5  7  9 11 13 15 17]
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [35]:
n2 = np.random.randint(0, 10, (2,5))
print(n2)
n2.resize(2,6)
print(n2)

[[4 9 1 2 2]
 [7 0 5 9 5]]
[[4 9 1 2 2 7]
 [0 5 9 5 0 0]]


In [38]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.arange(10, 19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [41]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [42]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [44]:
a1 = np.array([[1,2,3],
              [4,5,6]])
a2 = np.array([[1,2,3],
              [4,5,6]])

In [46]:
np.vstack([a1, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
np.hstack([a1, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [49]:
a1 = np.arange(0,10)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1, c1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]


# 배열 연산

In [53]:
a1 = np.arange(1,10)
print(a1)
print(np.add(a1, 10))
print(np.subtract(a1, 10))
print(np.negative(a1))
print(np.multiply(a1, 10))
print(np.divide(a1, 10))
print(np.floor_divide(a1, 10))
print(np.power(a1, 10))
print(np.mod(a1, 10))

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[10 20 30 40 50 60 70 80 90]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0 0 0 0 0 0 0 0 0]
[         1       1024      59049    1048576    9765625   60466176
  282475249 1073741824 3486784401]
[1 2 3 4 5 6 7 8 9]


In [54]:
a1 = np.random.randint(-10,10,size=5)
print(a1)
print(np.abs(a1))

[  7   3 -10  -3  -3]
[ 7  3 10  3  3]


In [56]:
print(np.square(np.abs(a1)))
print(np.sqrt(np.abs(a1)))

[ 49   9 100   9   9]
[2.64575131 1.73205081 3.16227766 1.73205081 1.73205081]


In [58]:
a1 = np.arange(1, 10)
print(np.power(a1, 5))

[    1    32   243  1024  3125  7776 16807 32768 59049]


In [62]:
print(np.sum(a1, axis=0))
print(np.mean(a1))
print(np.min(a1))
print(np.max(a1))

45
5.0
1
9


In [64]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.sort(a1))
print(np.argsort(a1))

[4 4 8 3 4 7 7 7 3 9]
[3 3 4 4 4 7 7 7 8 9]
[3 8 0 1 4 5 6 7 2 9]
