<a href="https://colab.research.google.com/github/fnzl54/Python_study/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch

# numpy review

In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)
print(t.ndim)
print(t.shape)
print(t[0], t[-1])
print(t[2:5])

[0. 1. 2. 3. 4. 5. 6.]
1
(7,)
0.0 6.0
[2. 3. 4.]


In [ ]:
# pytorch
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)
print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[-1])
print(t[2:5])

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(6.)
tensor([2., 3., 4.])


# broadcasting, mean

In [ ]:
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([2,2])
print(m1+m2)

tensor([5., 5.])


In [ ]:
#vector + scalar
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([12])
print(m1+m2)

tensor([15., 15.])


In [ ]:
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([[12], [23]])
print(m1+m2)

tensor([[15., 15.],
        [26., 26.]])


In [ ]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])
print('matrix multiplication : ', m1.matmul(m2))
print('multiplication', m1.mul(m2))

matrix multiplication :  tensor([[ 5.],
        [11.]])
multiplication tensor([[1., 2.],
        [6., 8.]])


In [ ]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


In [ ]:
print(t.max())
print(t.max(dim=0))
print(t.max(dim=1))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


# view(reshape)

In [ ]:
t = np.array([[[0,1,2],
               [3,4,5]],
              [[6,7,8],
               [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [ ]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


# squeeze

In [26]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


In [27]:
ft = torch.tensor([0,1,2])
print(ft.shape)
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

torch.Size([3])
tensor([[0, 1, 2]])
torch.Size([1, 3])
tensor([[0],
        [1],
        [2]])
torch.Size([3, 1])


# type casting, concatenate, stacking

In [29]:
lt = torch.LongTensor([1,2,3,4])
print(lt)
print(lt.float())
bt = torch.ByteTensor([True, False, True, False])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 1, 0], dtype=torch.uint8)
tensor([1, 0, 1, 0])
tensor([1., 0., 1., 0.])


In [30]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[1,2], [3,4]])
print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [1., 2.],
        [3., 4.]])
tensor([[1., 2., 1., 2.],
        [3., 4., 3., 4.]])


In [33]:
x = torch.FloatTensor([1,2])
y = torch.FloatTensor([3,4])
z = torch.FloatTensor([5,6])
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 3., 5.],
        [2., 4., 6.]])


# ones and zeros, in-place operation

In [34]:
x = torch.FloatTensor([[0,1,2], [2,1,0]])
print(x)
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [35]:
x = torch.FloatTensor([[1,2], [3,4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
